### ISSUE TITLE
Uploading manifest from https website with self-signed SSL certificate doesn't work

### ISSUE THREAD

**Issue by Pigeo** [dnoneill/annonatate-sourcecode#37]
Trying to upload the following manifest in Annonatate doesn't work : https://bcl-180.unice.fr:11280/iiif/ALMC3/manifest

However, trying to upload the very same manifest from another web server works : https://bcl.cnrs.fr/iiif/ALMC3/manifest.json

The only difference is that the former has a self-signed SSL certificate, whereas the second one has a "real" SSL certificate, signed from an official authority.

=> Could you please allow uploading manifests from URLs of servers with self-signed SSL certificates ?

Alternatively, you may consider providing an "unsecure" version of Annonatate in http (without the -s), because there may be some public IIIF servers that aren't in HTTPS, and I don't see the point in forcing everyone to have their public IIIF servers in HTTPS.

Thanks

**Comment by dnoneill** [comment]
@Pigeo I have tried going to https://bcl-180.unice.fr:11280/iiif/ALMC3/manifest in the browser. The problem I am having is I can't actually load that URL, it never loads. https://bcl.cnrs.fr/iiif/ALMC3/manifest.json loads just fine in the browser and from what I can tell that is the difference.

**Comment by Pigeo** [comment]
It's because [bcl-180.unice.fr](https://bcl-180.unice.fr:11280/iiif/ALMC3/manifest) server is currently using a self-signed SSL certificate, that's why your browser is blocking by default the loading of this URL, for security reasons, because it has flagged this web server as "unsecure" due to this self-signed SSL certificate. Since there's no real risk (it's just about downloading an IIIF manifest text file - no login / password, no sensitive information transmitted - but the browser doesn't know about that), you just need to tell your browser that you're understanding the risk and willing to continue loading the page. Here is how to do that for most commonly used browsers: https://www.vultr.com/docs/how-to-bypass-the-https-warning-for-self-signed-ssl-tls-certificates/ (it's super easy to do with Firefox or Safari, while Google Chrome makes things more complicated). Once you've done that once, your browser will keep the exception in memory, and you'll be able to load any other URLs on this same server without being blocked again (and thus you'll also be able to use this IIIF manifest from within Annonatate)

**Comment by dnoneill** [comment]
@Pigeo I have fixed the other two issues and deployed them. Right now because of the security risk to our servers from accepting a self-signed SSL certificate we won't be allowing this at this time. I would also caution against using this kind of certificate. I think it is really going to be hard to find a system that will allow them which takes away from some of the use of IIIF. Viewers like Mirador, UV, Clover and OpenSeadragon all don't allow this kind of certificate.

**Comment by sf7320** [comment]
Hello @dnoneill, first of all, thank you so much for your quick fix of the other two issues! 🙂

Concerning this issue about self-signed SSL certificates:
- We are using both Mirador and UV on this very same self-signed IIIF server, without any problem, they work like a charm: https://projectmirador.org/embed/?iiif-content=https://bcl-180.unice.fr:11280/iiif/ALMC3/manifest and http://universalviewer.io/uv.html?manifest=https://bcl-180.unice.fr:11280/iiif/ALMC3/manifest . Currently, the only IIIF web app that causes us problems with our self-signed IIIF server is Annonatate, hence the creation of this issue… no other problems found so far.
- Some IIIF Viewers, such as [UV](http://universalviewer.io) even allow the use of IIIF servers without any SSL certificates, by providing an HTTP alternative version of their HTTPS Viewer (just replace `https://` with `http://` at the beginning of the IIIF Viewer's URL)
- Now, about your "security risk to [y]our servers from accepting a self-signed SSL certificate" concerns, *theoretically*, I could ask for a real SSL certificate from a reputed certification authorities, such as [Let's Encrypt](https://letsencrypt.org/fr/), and install it on our IIIF server, but I don't see how that would make things more secure for you?? On our side, it would still be the same IIIF Server, hosting and serving the same files… (And I said ***theoretically*** because actually I tried that, and the thing is we can't use SSL certificates from [Let's Encrypt](https://letsencrypt.org/fr/) on our servers because our DNS provider is blocking them 😒 so we have to wait and to go for expensive SSL certificates instead...)
- The official [IIIF standard](https://iiif.io/) doesn't say that HTTPS / SSL should be mandatory for any IIIF Viewer nor any IIIF Server, and I think it's a bad idea to force imposing HTTPS to anybody, like a spreading cancer, particularly for certain uses where it's not really necessary and doesn't add much (in our case here: public IIIF Viewer accessing a public anonymous IIIF Server, having no reputation, without any login/password, and hosting no sensitive images) : issuing real SSL certificates from certification authorities and maintaining them (because they must be renewed every year) is a painful activity (takes time and often also costs money), thus this goes against any mass adoption of the IIIF standard by the general public (I'm thinking here about small non-profit associations, hobbyist individuals, etc.)
- Let's rewind a bit and go back to the origins: at the beginning, modern web browsers started to block loading mixed content (i.e. HTTP content within an HTTPS web page) as a security measure in order to protect the **internet user** (i.e. the client) against any potential attack, such as "man-in-the-middle", while browsing on sensitive web sites (banks, web sites with login/password, etc.). But even in latest versions of any web browser, the end user remains in control, and can add a safety exception to locally override such security one some specific local / private web sites that use self-signed SSL certificates, where the end user knows it's safe and assumes the risk. So, in this issue, I was just asking to do the same in Annonatate: display a warning message, and ask the end user whether we wants to assume the risk and continue or not.

By the way, here's what we did at the end, as a work-around to this issue, in order to get Annonatate working on our self-signed "unsecure" IIIF server: we put a copy of our Manifests on another static web server (one having a "good" SSL certificate), and we uploaded that copy in Annonatate, and now everything is fine, and Annonatate is retrieving the IIIF Images from our self-signed "unsecure" IIIF server like a charm (since the content of the Manifest copy still points to our original self-signed IIIF server...), so it really wouldn't need much to make Annonatate usable with a self-signed IIIF server.

**Comment by dnoneill** [comment]
<img width="922" alt="Screenshot 2023-07-26 at 1 00 00 PM" src="https://github.com/dnoneill/annonatate-sourcecode/assets/19173991/5193bb69-d1aa-41df-b391-c486906b3aad">
<img width="917" alt="Screenshot 2023-07-26 at 12 59 28 PM" src="https://github.com/dnoneill/annonatate-sourcecode/assets/19173991/a9f92f89-550c-4a60-9584-e00f5462131d">

**Comment by Pigeo** [comment]
> When I loaded both those links (Mirador and UV) the views didn't work by default. I have attached screenshots.

That's perfectly normal and expected (default behaviour of any modern browser): it's just because you first need to set up an exception for this self-signed certificate server in your browser's settings, but then it will work.

FYI, if you first navigate to https://bcl-180.unice.fr:11280/iiif/ALMC3/manifest with your browser, it is going to block the page loading and tell you that the certificate is self-signed. There, you can add an exception (depending on which browser you use, it involves something like clicking on several buttons such as "I understand the risk and I'm willing to continue"). Once this exception is stored in your browser's preferences, you can then go to Mirador or UV (URLs provided above) and you'll see it's going to work fine 😉

**Comment by Pigeo** [comment]
> I would be happy to get you and your colleagues set up with an instance of Annonatate that would do this. The source code is obviously open source and there are very few steps to get it working.

Thanks for proposing your help. For the moment I don't think it will be necessary: we're going to request a real SSL certificate from our IT staff. This is going to take a while before it's operational, but in the meantime we've managed to get Annonatate working on our self-signed "unsecure" server right now, thanks to work-around described above, so it's not blocking us in our work.
