### ISSUE TITLE
Thumbnails not working (wrong URLs generated)

### ISSUE THREAD

**Issue by Pigeo** [dnoneill/annonatate-sourcecode#38]
After having successfully uploaded my manifest from https://bcl.cnrs.fr/iiif/ALMC3/manifest.json I'm trying to start annotating from the Home tab.

Thumbnails are not displayed properly (blank rectangles in place of thumbnails).

By looking in the developper console of my browser, I see that the URLs that Annonatate has generated for these thumbnails are wrong. 
Example of such an erroneous thumbnail URL generated by Annonatate : https://bcl-180.unice.fr:11280/iiif/ALMC3/ALMC_3_0329_Q1881/0/default.jpg/0/default.jpg/0/default.jpg
(notice that there's 3 times repetition of "/0/default.jpg" at the end of the URL)

Whereas the correct URL would be somehting like: https://bcl-180.unice.fr:11280/iiif/ALMC3/ALMC_3_0329_Q1881/full/90,/0/default.jpg

**Comment by dnoneill** [comment]
@Pigeo I looked at this issue. What I found is the thumbnail generated for this manifest. What I got is: https://bcl-180.unice.fr:11280/iiif/ALMC3/ALMC_3_0001/full/full/0/default.jpg. When I try to go to that URL in a browser. It never loads. Would you mind linking to the repository with which you are having this problem? Because currently I am unsure of how you are getting this problem.

**Comment by Bcl7320** [comment]
Hello @dnoneill, thank you for your quick reply! I now realise my initial message was a little bit ambiguous, so let me send you those 2 screenshots attached: 
<img width="1638" alt="working" src="https://github.com/dnoneill/annonatate-sourcecode/assets/140181688/1dbc953f-4a60-4f52-b488-54249f136d9b">
<img width="1638" alt="not working" src="https://github.com/dnoneill/annonatate-sourcecode/assets/140181688/9ff662d6-4cbf-4b6a-ad36-751fd59464c8">
Please compare screenshot 1 and screenshot 2, and I think the issue will be clearer for you.

**Comment by Bcl7320** [comment]
Also, please note that our IIIF server is currently using a self-signed SSL certificate, that's why your browser is blocking by default the loading of those URLs, for security reasons, because it has flagged our web server as "unsecure" due to this self-signed SSL certificate. Since there's no real risk (it's just about downloading some IIIF pictures - no login / password, no sensitive information transmitted - but the browser doesn't know about that), you just need to tell your browser that you're understanding the risk and willing to continue loading the page. Here is how to do that for most commonly used browsers: https://www.vultr.com/docs/how-to-bypass-the-https-warning-for-self-signed-ssl-tls-certificates/ (it's super easy to do with Firefox or Safari, while Google Chrome makes things more complicated). Once you've done that once, your browser will keep the exception in memory, and you'll be able to load any other URLs on this same server without being blocked again (and thus you'll also be able to use this IIIF server from within Annonatate)

**Comment by Bcl7320** [comment]
> Would you mind linking to the repository with which you are having this problem? Because currently I am unsure of how you are getting this problem

Here it is : https://github.com/pag06/atlas

**Comment by Pigeo** [comment]
Hello @dnoneill, thank you for your quick reply! I now realise my initial message was a little bit ambiguous, so let me send you those 2 screenshots attached: 
<img width="1638" alt="working" src="https://github.com/dnoneill/annonatate-sourcecode/assets/140181688/1dbc953f-4a60-4f52-b488-54249f136d9b">
<img width="1638" alt="not working" src="https://github.com/dnoneill/annonatate-sourcecode/assets/140181688/9ff662d6-4cbf-4b6a-ad36-751fd59464c8">
Please compare screenshot 1 and screenshot 2, and I think the issue will be clearer for you.

**Comment by Pigeo** [comment]
Also, please note that our IIIF server is currently using a self-signed SSL certificate, that's why your browser is blocking by default the loading of those URLs, for security reasons, because it has flagged our web server as "unsecure" due to this self-signed SSL certificate. Since there's no real risk (it's just about downloading some IIIF pictures - no login / password, no sensitive information transmitted - but the browser doesn't know about that), you just need to tell your browser that you're understanding the risk and willing to continue loading the page. Here is how to do that for most commonly used browsers: https://www.vultr.com/docs/how-to-bypass-the-https-warning-for-self-signed-ssl-tls-certificates/ (it's super easy to do with Firefox or Safari, while Google Chrome makes things more complicated). Once you've done that once, your browser will keep the exception in memory, and you'll be able to load any other URLs on this same server without being blocked again (and thus you'll also be able to use this IIIF server from within Annonatate)

**Comment by Pigeo** [comment]
> Would you mind linking to the repository with which you are having this problem? Because currently I am unsure of how you are getting this problem

Here it is : https://github.com/pag06/atlas
