### ISSUE TITLE
unknown error 'value'

### ISSUE THREAD

**Issue by raphaelemplus** [dnoneill/annonatate-sourcecode#41]
Once an annotation is created, this following error appeared on the 'homepage'

<img width="1408" alt="homepage" src="https://github.com/dnoneill/annonatate-sourcecode/assets/140806634/37476c4b-8d92-423c-9e11-2abefeee9ca9">

When navigated to 'search', an Internal Server Error is triggered.

<img width="1411" alt="search" src="https://github.com/dnoneill/annonatate-sourcecode/assets/140806634/6fccae5d-9ab8-4929-adb2-68ddc78a183f">

No error message is printed in the browser console.

I am using [https://annonatate.fly.dev](https://annonatate.fly.dev).  Is it necessary to host my own instance in order to make it work?

**Comment by dnoneill** [comment]
@raphaelemplus It will not help. Based on what I am setting there is something hinky with the data in your repository. I am doing some quick troubleshooting right now. I will get back to you as soon as I have an answer.

**Comment by dnoneill** [comment]
@raphaelemplus I am so sorry for that error. Turns out I had not accounted in search for the data structure of vocab tags coming from Annotorious. I am pretty sure it changed with the update of annotorious and I missed that fact. The new code has been deployed to annoantate.fly.dev and hopefully you shouldn't be having any problems again. Please let me know if you continue to encounter issues. Thanks so much for reaching out about this problem.
